// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: user.proto

package users

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PostDataServiceClient is the client API for PostDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostDataServiceClient interface {
	Process(ctx context.Context, in *PostDataRequest, opts ...grpc.CallOption) (*PostDataResponse, error)
}

type postDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostDataServiceClient(cc grpc.ClientConnInterface) PostDataServiceClient {
	return &postDataServiceClient{cc}
}

func (c *postDataServiceClient) Process(ctx context.Context, in *PostDataRequest, opts ...grpc.CallOption) (*PostDataResponse, error) {
	out := new(PostDataResponse)
	err := c.cc.Invoke(ctx, "/users.PostDataService/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostDataServiceServer is the server API for PostDataService service.
// All implementations must embed UnimplementedPostDataServiceServer
// for forward compatibility
type PostDataServiceServer interface {
	Process(context.Context, *PostDataRequest) (*PostDataResponse, error)
	mustEmbedUnimplementedPostDataServiceServer()
}

// UnimplementedPostDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPostDataServiceServer struct {
}

func (UnimplementedPostDataServiceServer) Process(context.Context, *PostDataRequest) (*PostDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedPostDataServiceServer) mustEmbedUnimplementedPostDataServiceServer() {}

// UnsafePostDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostDataServiceServer will
// result in compilation errors.
type UnsafePostDataServiceServer interface {
	mustEmbedUnimplementedPostDataServiceServer()
}

func RegisterPostDataServiceServer(s grpc.ServiceRegistrar, srv PostDataServiceServer) {
	s.RegisterService(&PostDataService_ServiceDesc, srv)
}

func _PostDataService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostDataServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.PostDataService/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostDataServiceServer).Process(ctx, req.(*PostDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostDataService_ServiceDesc is the grpc.ServiceDesc for PostDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.PostDataService",
	HandlerType: (*PostDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _PostDataService_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
